### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by malit0ss** [dev-lu/osint_toolkit#15]
src/components/ioc-analyzer/services/multi/Alienvault.jsx 290:41
Module parse failed: Unexpected token (290:41)
You may need an appropriate loader to handle this file type.
|       columnNumber: 19
|     }
>   }, "Pulses"), result.pulse_info.pulses?.map(function (pulse) {
|     return /*#__PURE__*/React.createElement(Chip, {
|       key: pulse.id,

**Comment by dev-lu** [comment]
Did you use Docker for deployment?

**Comment by malit0ss** [comment]
> Did you use Docker for deployment?

manually and Docker method and the isue is the same

**Comment by dev-lu** [comment]
Then I would guess you browser does not support JavaScript optional chaining.
Please make sure your browser is up to date.

Supported browsers are:
Chrome - Version 80 or newer
Edge - Version 80 or newer
Firefox - Version 74 or newer
Opera - Version 67 or newer
Safari - Version 13.1 or newer

**Comment by malit0ss** [comment]
thats not de problem because i tried with diferent browser with the latest version updated and the issues persists

**Comment by dev-lu** [comment]
Did you try different browsers with Docker or local deployment? For local deployment, you need Node version 17 or higher.

**Comment by malit0ss** [comment]
both methods of installation
And i have node v18.17.0

**Comment by malit0ss** [comment]
i cant fix the issue

**Comment by dev-lu** [comment]
I tried to reproduce the issue on 3 different machines, with 3 different operating systems without any problems. The only solution I know at the moment is to remove optional chaining from the application, but I don't want to do this, to be honest.

**Comment by malit0ss** [comment]
how can I contact you personally?
