### ISSUE TITLE
Somehow I am still receiving Network Error

### ISSUE THREAD

**Issue by Blason** [dev-lu/osint_toolkit#16]
Hi,

It worked perfectly fine for me and then I tried deploying in my cloud which has a one Public NIC and other is private NIC. I changed it to Private NIC and docker came up appropriately. Now I am trying to access using Private IP and it gives me same netork error..
Uncaught runtime errors:
×
ERROR
Network Error
ERROR
Network Error
ERROR
Network Error
[logs.txt](https://github.com/dev-lu/osint_toolkit/files/12236942/logs.txt)

ERROR
Network Error

And here are the logs

**Comment by Blason** [comment]
ok let me check and quickly revert

**Comment by Blason** [comment]
I now changed the yml fle like this and testing
version: "3.3"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://0.0.0.0:8000  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


And when access port 8000 here is the response
{"detail":"Not Found"}

**Comment by Blason** [comment]
One things I noticed when I checked the logs is - the applicaiton is trying to listen on docker interface

Compiled successfully!

You can now view osint-toolkit in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.18.0.3:3000

Note that the development build is not optimized.
To create a production b

uild, use npm run build.

webpack compiled successfully

CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS         PORTS                                       NAMES
af5cbc333f28   osint_toolkit_backend    "uvicorn main:app --…"   6 hours ago   Up 6 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   backend
9408de9ec84e   osint_toolkit_frontend   "docker-entrypoint.s…"   6 hours ago   Up 6 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   frontend

**Comment by dev-lu** [comment]
This is normal behaviour of the React development server and can be ignored. Important is where your frontend tries to connect to. The configuration you posted before is not correct. 
0.0.0.0:8000 is not a valid endpoint for the frontend to connect to. BACKEND_URL must be an endpoint, that you can reach through your browser. Keep in mind that you should not deploy the application to the public, as there is no authentication in place.

**Comment by Blason** [comment]
In that case local host should be fine right instead of any ip address
since it's a internal communication?

And again I m hiding it behind nginx with authelia as mfa for better
security

**Comment by dev-lu** [comment]
No, it is not internal communication. It is a web application with a frontend that runs in your browser. This means your browser needs to communicate with the backend. The backend URL argument tells your browser where to send the requests to. If your backend is located on a remote machine and "localhost" is configured as the backend URL, then your browser sends the requests to your local machine and not to the remote host. As stated in the readme file, this project is still a prototype at a very early stage and is currently not suitable for deployment on remote machines.

**Comment by Blason** [comment]
I see that means my machine needs to communicate with server on port 3000 as well as 8000?

**Comment by dev-lu** [comment]
Yes this is right.
