### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by doddy2912** [dev-lu/osint_toolkit#17]
What if I want to add SSL to create a domain?
Where should I add the configuration?

**Comment by Blason** [comment]
I am not sure though but you can build a Nginx reverse proxy in front of it. This is what even I am trying but unfortunately I am stuck in other issue. However this option is pretty valid

**Comment by dev-lu** [comment]
There is no way to configure SSL. However, you can use a reverse proxy as stated before. But keep in mind that this application is still at a very early stage and should not be deployed publicly.
