### ISSUE TITLE
Setting and edit does not working

### ISSUE THREAD

**Issue by KhaledEid020** [dev-lu/osint_toolkit#18]
here is my problem
https://github.com/dev-lu/osint_toolkit/assets/46486159/da7acb0f-a71c-46f0-a0ce-8c79eb1c7d06

can you help, please?

**Comment by dev-lu** [comment]
There was a bug with a blocking request. Try cloning the latest version of the repo and build a new version of the image with `docker compose up --build`.

**Comment by KhaledEid020** [comment]
Thanks!
worked
