### ISSUE TITLE
Getting runtime error when IP address is analyzed

### ISSUE THREAD

**Issue by fcarras** [dev-lu/osint_toolkit#19]
![Screenshot from 2023-08-10 13-45-18](https://github.com/dev-lu/osint_toolkit/assets/141858980/ecdd0e79-e29e-4937-a99d-86aea21eb5ce)

When 1.1.1.1 and 8.8.8.8 are input as test, everything runs fine. However, trying other IP address (such as my IP) I'm getting an runtime error.

**Comment by dev-lu** [comment]
Hi, thanks for reporting this bug. It should be fixed now. Please clone the latest version of this repository and try again.
