### ISSUE TITLE
Service page won't render

### ISSUE THREAD

**Issue by whapa** [dev-lu/osint_toolkit#26]
I've done all steps to install and run both backend and frontend. But the page won't render to me. Just loading...
Im using virtualbox on a Kalilinux and internal firefox to show the page..
Any tip?

![image](https://github.com/dev-lu/osint_toolkit/assets/158293521/6ae49931-cfc8-4e5e-9eb0-b169bfa5292d)

**Comment by dev-lu** [comment]
Did you receive any error messages?

**Comment by whapa** [comment]
![image](https://github.com/dev-lu/osint_toolkit/assets/158293521/16ec622a-98d8-4eaf-93ef-56f9163526fb)
More evidences..

**Comment by dev-lu** [comment]
Hi, it's very hard to tell what the problem is just from your screenshots. 
However, I highly recommend using Docker for installation because deploying from source can cause a lot of problems due to all the dependencies that must match perfectly.

**Comment by whapa** [comment]
Ok, i will try use docker. Thanks!

**Comment by mikgallo** [comment]
Please can you write a guide for installation on kali?

**Comment by mikgallo** [comment]
How use docker for installation?

**Comment by dev-lu** [comment]
Install Docker: https://docs.docker.com/engine/install/debian/

Deploy OSINT Toolkit with docker:
1. Download the repository and extract the files
2. Navigate to the directory where the `docker-compose.yaml` file is located
3. If you deploy the app on a remote machine, set the `BACKEND_URL` argument in the Compose file to the remote machines IP address
4. Run the following command: `docker-compose up -d`
5. Once the container is running, you can access the app in your browser at http://localhost:3000
