### ISSUE TITLE
Server Backend error Network

### ISSUE THREAD

**Issue by ghossh12** [dev-lu/osint_toolkit#27]
Hello ,

I have a problem after deploying ONSINT_TOOLKITS on docker here is how the page displays , 
![osi,nt_toolkits](https://github.com/dev-lu/osint_toolkit/assets/159398331/78df0be0-ba23-4e27-a293-12c26e3656f7)
 Voici mon fichier de configuration docker :

version: "3.3"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8010:8010"
    volumes:
      - ./data:/backend/database/data
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://172.19.21.58:8010  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
Can you please help me to solve this problem?

**Comment by ghossh12** [comment]
Thank you, it works now, but do you have an alternative to secure access to the web interface?

**Comment by dev-lu** [comment]
This software is designed for local use only, as it lacks an authentication system. It's not recommended to deploy it publicly, which is why HTTPS isn't necessary. If you need HTTPS anyway, using a reverse proxy would be the recommended approach.
