### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by h4zhir** [dev-lu/osint_toolkit#28]
Hello i have a question can i host this container somewhere for free ?

**Comment by dev-lu** [comment]
Please be aware that this software is intended for local deployment only. I do not provide support for hosting, deployment, or other non-bug-related topics through GitHub issues.

**Comment by h4zhir** [comment]
> Please be aware that this software is intended for local deployment only. I do not provide support for hosting, deployment, or other non-bug-related topics through GitHub issues.

Alright thanks
