### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by danger112233** [dev-lu/osint_toolkit#31]
Hi dev,

First of thank for creating such a web based beautiful tool. Im very curious to download the tools,

Actually I never used docker before, it little bit tough learn quickly, During installation I have so many doubt and error.

Could you guide how to download the tools that would be better.

Even though I followed as you instructed but still im facing issue.

![Screenshot 2024-04-01 212057](https://github.com/dev-lu/osint_toolkit/assets/63256615/9a3b0195-fae7-4e44-be37-76159571eb88)
![Screenshot 2024-04-01 211948](https://github.com/dev-lu/osint_toolkit/assets/63256615/08834edc-2ea0-4216-9e6f-e9cca41727d5)

Pls kindly help me on this.

**Comment by dev-lu** [comment]
Hi, sorry for getting back to you late. I've never encountered this error before, and after some research, it seems that the problem is caused by a bug from Docker on Windows. For further details, refer to this GitHub issue: https://github.com/docker/for-win/issues/13611.

**Comment by danger112233** [comment]
Hi Dev,

I newly installed latest docker in my windows machine, but still I'm facing issue, is there specific docker version that you recommend.

**Comment by danger112233** [comment]
Hi Dev,

![Screenshot 2024-04-06 153926](https://github.com/dev-lu/osint_toolkit/assets/63256615/4ae75075-4403-4553-8156-d760af7f8a26)

1. How long it will take,  for the last half hours it will be same 18/21  
2. NPM error
![Screenshot 2024-04-06 154309](https://github.com/dev-lu/osint_toolkit/assets/63256615/2779188f-e386-4607-be0d-e02aa0df7151)

**Comment by dev-lu** [comment]
Hi danger112233, 

please try it again using the following command `docker-compose build --no-cache`
