### ISSUE TITLE
AI Assistant not working

### ISSUE THREAD

**Issue by sscoconutree** [dev-lu/osint_toolkit#32]
Hi,

I put in my OpenAI API key and it seems the AI Assistant feature is not working.

I even tried the sample snippets and it doesn't work at all since there were no results returned.

![image](https://github.com/dev-lu/osint_toolkit/assets/59388557/200e8168-b96c-42de-940d-101964269500)

**Comment by dev-lu** [comment]
Hello @sscoconutree, 

I have made some changes in dc22009 that should fix this behavior. Please update your installation and try again.

Best regards, 
dev-lu
