### ISSUE TITLE
Uncaught runtime errors: ERROR Network Error ERROR

### ISSUE THREAD

**Issue by UserCr4ig** [dev-lu/osint_toolkit#5]
Hi,

I've attempted to install it on 2 separate servers, and each time I encountered a screen displaying the following:

Uncaught runtime errors: ERROR
Network Error ERROR
Network Error ERROR
Network Error ERROR

I've tried to analyze the code, but I can't figure out the cause of this error.

**Comment by dev-lu** [comment]
Hi, the cause of this error is CORS. You can check it in your browser console. 
Did you use Docker or do a manual installation? 

For Docker:
Uncomment these two lines and insert the IP and Port of the server where the backend is located.
```yaml
    environment:
      - BACKEND_URL=http://<IP_ADDRESS>:<PORT> # Backend URL without trailing slash
```

For manual installation:
Set an environment variable on the machine where your frontend is installed:
```bash
export REACT_APP_BACKEND_URL="http://<IP>:<PORT>"
```

**Comment by UserCr4ig** [comment]
Yes i use docker, il try this and check if it patches the issue

**Comment by UserCr4ig** [comment]
It didn't work. I've tried with localhost:8000 and 192.168.1.10:8000 (where my backend is located)

**Comment by dev-lu** [comment]
Please take a look at your browser console to see where the frontend is attempting to connect to.
