### ISSUE TITLE
White blank page

### ISSUE THREAD

**Issue by victorreynaldi** [dev-lu/osint_toolkit#6]
White blank page. Why?

**Comment by dev-lu** [comment]
Could you please give more context?

**Comment by victorreynaldi** [comment]
I get white blank page when I open url http://myipserver using browser. And when I do curl -i http://myserverip:3000, I get resutl curl: (56) Recv failure: Connection reset by peer

**Comment by dev-lu** [comment]
Maybe your firewall is blocking the connection to port 3000.
But keep in mind: The application is not designed for deployment on a public VPS. There is no authentication in place to protect your data. I highly recommend just running the application on your local machine via Docker.
