### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by PawnStorm0x** [dev-lu/osint_toolkit#8]
i have a error after install with docker 
..........................................................
Failed to compile
./src/components/ioc-analyzer/services/multi/Alienvault.jsx 290:41
Module parse failed: Unexpected token (290:41)
You may need an appropriate loader to handle this file type.
|       columnNumber: 19
|     }
>   }, "Pulses"), result.pulse_info.pulses?.map(function (pulse) {
|     return /*#__PURE__*/React.createElement(Chip, {
|       key: pulse.id,
This error occurred during the build time and cannot be dismissed.

**Comment by dev-lu** [comment]
Did you change any files? Please clone the repository again and give it another try.

**Comment by PawnStorm0x** [comment]
i change nothing i installed it with Docker and have this error

**Comment by dev-lu** [comment]
I have tried it several times on different machines now, with no problems. However, I encounter a similar error when I use your forked version.

**Comment by malit0ss** [comment]
have the same error and i dont change any file
